spr888-ctfd/CTFd/forms/email.py
from wtforms import TextAreaField
from wtforms.validators import InputRequired

from CTFd.forms import BaseForm
from CTFd.forms.fields import SubmitField


class SendEmailForm(BaseForm):
    text = TextAreaField("Message", validators=[InputRequired()])
    submit = SubmitField("Send")

spr888-ctfd/CTFd/admin/__init__.py
import csv  # noqa: I001
import datetime
import os
from io import StringIO

from flask import Blueprint, abort
from flask import current_app as app
from flask import (
    jsonify,
    redirect,
    render_template,
    render_template_string,
    request,
    send_file,
    url_for,
)

admin = Blueprint("admin", __name__)

# isort:imports-firstparty
from CTFd.admin import challenges  # noqa: F401,I001
from CTFd.admin import notifications  # noqa: F401,I001
from CTFd.admin import pages  # noqa: F401,I001
from CTFd.admin import scoreboard  # noqa: F401,I001
from CTFd.admin import statistics  # noqa: F401,I001
from CTFd.admin import submissions  # noqa: F401,I001
from CTFd.admin import teams  # noqa: F401,I001
from CTFd.admin import users  # noqa: F401,I001
from CTFd.cache import (
    cache,
    clear_all_team_sessions,
    clear_all_user_sessions,
    clear_challenges,
    clear_config,
    clear_pages,
    clear_standings,
)
from CTFd.models import (
    Awards,
    Challenges,
    Configs,
    Notifications,
    Pages,
    Solves,
    Submissions,
    Teams,
    Tracking,
    Unlocks,
    Users,
    db,
)
from CTFd.utils import config as ctf_config
from CTFd.utils import get_app_config, get_config, set_config
from CTFd.utils.csv import dump_csv, load_challenges_csv, load_teams_csv, load_users_csv
from CTFd.utils.decorators import admins_only
from CTFd.utils.exports import background_import_ctf
from CTFd.utils.exports import export_ctf as export_ctf_util
from CTFd.utils.security.auth import logout_user
from CTFd.utils.uploads import delete_file
from CTFd.utils.user import is_admin


@admin.route("/admin", methods=["GET"])
def view():
    if is_admin():
        return redirect(url_for("admin.statistics"))
    return redirect(url_for("auth.login"))


@admin.route("/admin/plugins/<plugin>", methods=["GET", "POST"])
@admins_only
def plugin(plugin):
    if request.method == "GET":
        plugins_path = os.path.join(app.root_path, "plugins")

        config_html_plugins = [
            name
            for name in os.listdir(plugins_path)
            if os.path.isfile(os.path.join(plugins_path, name, "config.html"))
        ]

        if plugin in config_html_plugins:
            config_html = open(
                os.path.join(app.root_path, "plugins", plugin, "config.html")
            ).read()
            return render_template_string(config_html)
        abort(404)
    elif request.method == "POST":
        for k, v in request.form.items():
            if k == "nonce":
                continue
            set_config(k, v)
        with app.app_context():
            clear_config()
        return "1"


@admin.route("/admin/import", methods=["GET", "POST"])
@admins_only
def import_ctf():
    if request.method == "GET":
        start_time = cache.get("import_start_time")
        end_time = cache.get("import_end_time")
        import_status = cache.get("import_status")
        import_error = cache.get("import_error")
        return render_template(
            "admin/import.html",
            start_time=start_time,
            end_time=end_time,
            import_status=import_status,
            import_error=import_error,
        )
    elif request.method == "POST":
        backup = request.files["backup"]
        background_import_ctf(backup)
        return redirect(url_for("admin.import_ctf"))


@admin.route("/admin/export", methods=["GET", "POST"])
@admins_only
def export_ctf():
    backup = export_ctf_util()
    ctf_name = ctf_config.ctf_name()
    day = datetime.datetime.now().strftime("%Y-%m-%d_%T")
    full_name = "{}.{}.zip".format(ctf_name, day)
    return send_file(
        backup, cache_timeout=-1, as_attachment=True, attachment_filename=full_name
    )


@admin.route("/admin/import/csv", methods=["POST"])
@admins_only
def import_csv():
    csv_type = request.form["csv_type"]
    # Try really hard to load data in properly no matter what nonsense Excel gave you
    raw = request.files["csv_file"].stream.read()
    try:
        csvdata = raw.decode("utf-8-sig")
    except UnicodeDecodeError:
        try:
            csvdata = raw.decode("cp1252")
        except UnicodeDecodeError:
            csvdata = raw.decode("latin-1")
    csvfile = StringIO(csvdata)

    loaders = {
        "challenges": load_challenges_csv,
        "users": load_users_csv,
        "teams": load_teams_csv,
    }

    loader = loaders[csv_type]
    reader = csv.DictReader(csvfile)
    success = loader(reader)
    if success is True:
        return redirect(url_for("admin.config"))
    else:
        return jsonify(success), 500


@admin.route("/admin/export/csv")
@admins_only
def export_csv():
    table = request.args.get("table")

    output = dump_csv(name=table)

    return send_file(
        output,
        as_attachment=True,
        max_age=-1,
        download_name="{name}-{table}.csv".format(
            name=ctf_config.ctf_name(), table=table
        ),
    )


@admin.route("/admin/config", methods=["GET", "POST"])
@admins_only
def config():
    # Clear the config cache so that we don't get stale values
    clear_config()

    configs = Configs.query.all()
    configs = {c.key: get_config(c.key) for c in configs}

    themes = ctf_config.get_themes()

    # Remove current theme but ignore failure
    try:
        themes.remove(get_config("ctf_theme"))
    except ValueError:
        pass

    force_html_sanitization = get_app_config("HTML_SANITIZATION")

    return render_template(
        "admin/config.html",
        themes=themes,
        **configs,
        force_html_sanitization=force_html_sanitization
    )


@admin.route("/admin/reset", methods=["GET", "POST"])
@admins_only
def reset():
    if request.method == "POST":
        require_setup = False
        logout = False
        next_url = url_for("admin.statistics")

        data = request.form

        if data.get("pages"):
            _pages = Pages.query.all()
            for p in _pages:
                for f in p.files:
                    delete_file(file_id=f.id)

            Pages.query.delete()

        if data.get("notifications"):
            Notifications.query.delete()

        if data.get("challenges"):
            _challenges = Challenges.query.all()
            for c in _challenges:
                for f in c.files:
                    delete_file(file_id=f.id)
            Challenges.query.delete()

        if data.get("accounts"):
            Users.query.delete()
            Teams.query.delete()
            require_setup = True
            logout = True

        if data.get("submissions"):
            Solves.query.delete()
            Submissions.query.delete()
            Awards.query.delete()
            Unlocks.query.delete()
            Tracking.query.delete()

        if data.get("user_mode") == "users":
            db.session.query(Users).update({Users.team_id: None})
            Teams.query.delete()

            clear_all_user_sessions()
            clear_all_team_sessions()

        if require_setup:
            set_config("setup", False)
            cache.clear()
            logout_user()
            next_url = url_for("views.setup")

        db.session.commit()

        clear_pages()
        clear_standings()
        clear_challenges()
        clear_config()

        if logout is True:
            cache.clear()
            logout_user()

        db.session.close()
        return redirect(next_url)

    return render_template("admin/reset.html")

spr888-ctfd/CTFd/plugins/challenges/__init__.py
from flask import Blueprint

from CTFd.models import (
    ChallengeFiles,
    Challenges,
    Fails,
    Flags,
    Hints,
    Solves,
    Tags,
    db,
)
from CTFd.plugins import register_plugin_assets_directory
from CTFd.plugins.flags import FlagException, get_flag_class
from CTFd.utils.uploads import delete_file
from CTFd.utils.user import get_ip


class BaseChallenge(object):
    id = None
    name = None
    templates = {}
    scripts = {}
    challenge_model = Challenges

    @classmethod
    def create(cls, request):
        """
        This method is used to process the challenge creation request.

        :param request:
        :return:
        """
        data = request.form or request.get_json()

        challenge = cls.challenge_model(**data)

        db.session.add(challenge)
        db.session.commit()

        return challenge

    @classmethod
    def read(cls, challenge):
        """
        This method is in used to access the data of a challenge in a format processable by the front end.

        :param challenge:
        :return: Challenge object, data dictionary to be returned to the user
        """
        data = {
            "id": challenge.id,
            "name": challenge.name,
            "value": challenge.value,
            "description": challenge.description,
            "attribution": challenge.attribution,
            "connection_info": challenge.connection_info,
            "next_id": challenge.next_id,
            "category": challenge.category,
            "state": challenge.state,
            "max_attempts": challenge.max_attempts,
            "type": challenge.type,
            "type_data": {
                "id": cls.id,
                "name": cls.name,
                "templates": cls.templates,
                "scripts": cls.scripts,
            },
        }
        return data

    @classmethod
    def update(cls, challenge, request):
        """
        This method is used to update the information associated with a challenge. This should be kept strictly to the
        Challenges table and any child tables.

        :param challenge:
        :param request:
        :return:
        """
        data = request.form or request.get_json()
        for attr, value in data.items():
            setattr(challenge, attr, value)

        db.session.commit()
        return challenge

    @classmethod
    def delete(cls, challenge):
        """
        This method is used to delete the resources used by a challenge.

        :param challenge:
        :return:
        """
        Fails.query.filter_by(challenge_id=challenge.id).delete()
        Solves.query.filter_by(challenge_id=challenge.id).delete()
        Flags.query.filter_by(challenge_id=challenge.id).delete()
        files = ChallengeFiles.query.filter_by(challenge_id=challenge.id).all()
        for f in files:
            delete_file(f.id)
        ChallengeFiles.query.filter_by(challenge_id=challenge.id).delete()
        Tags.query.filter_by(challenge_id=challenge.id).delete()
        Hints.query.filter_by(challenge_id=challenge.id).delete()
        Challenges.query.filter_by(id=challenge.id).delete()
        cls.challenge_model.query.filter_by(id=challenge.id).delete()
        db.session.commit()

    @classmethod
    def attempt(cls, challenge, request):
        """
        This method is used to check whether a given input is right or wrong. It does not make any changes and should
        return a boolean for correctness and a string to be shown to the user. It is also in charge of parsing the
        user's input from the request itself.

        :param challenge: The Challenge object from the database
        :param request: The request the user submitted
        :return: (boolean, string)
        """
        data = request.form or request.get_json()
        submission = data["submission"].strip()
        flags = Flags.query.filter_by(challenge_id=challenge.id).all()
        for flag in flags:
            try:
                if get_flag_class(flag.type).compare(flag, submission):
                    return True, "Correct"
            except FlagException as e:
                return False, str(e)
        return False, "Incorrect"

    @classmethod
    def solve(cls, user, team, challenge, request):
        """
        This method is used to insert Solves into the database in order to mark a challenge as solved.

        :param team: The Team object from the database
        :param chal: The Challenge object from the database
        :param request: The request the user submitted
        :return:
        """
        data = request.form or request.get_json()
        submission = data["submission"].strip()
        solve = Solves(
            user_id=user.id,
            team_id=team.id if team else None,
            challenge_id=challenge.id,
            ip=get_ip(req=request),
            provided=submission,
        )
        db.session.add(solve)
        db.session.commit()

    @classmethod
    def fail(cls, user, team, challenge, request):
        """
        This method is used to insert Fails into the database in order to mark an answer incorrect.

        :param team: The Team object from the database
        :param chal: The Challenge object from the database
        :param request: The request the user submitted
        :return:
        """
        data = request.form or request.get_json()
        submission = data["submission"].strip()
        wrong = Fails(
            user_id=user.id,
            team_id=team.id if team else None,
            challenge_id=challenge.id,
            ip=get_ip(request),
            provided=submission,
        )
        db.session.add(wrong)
        db.session.commit()


class CTFdStandardChallenge(BaseChallenge):
    id = "standard"  # Unique identifier used to register challenges
    name = "standard"  # Name of a challenge type
    templates = {  # Templates used for each aspect of challenge editing & viewing
        "create": "/plugins/challenges/assets/create.html",
        "update": "/plugins/challenges/assets/update.html",
        "view": "/plugins/challenges/assets/view.html",
    }
    scripts = {  # Scripts that are loaded when a template is loaded
        "create": "/plugins/challenges/assets/create.js",
        "update": "/plugins/challenges/assets/update.js",
        "view": "/plugins/challenges/assets/view.js",
    }
    # Route at which files are accessible. This must be registered using register_plugin_assets_directory()
    route = "/plugins/challenges/assets/"
    # Blueprint used to access the static_folder directory.
    blueprint = Blueprint(
        "standard", __name__, template_folder="templates", static_folder="assets"
    )
    challenge_model = Challenges


def get_chal_class(class_id):
    """
    Utility function used to get the corresponding class from a class ID.

    :param class_id: String representing the class ID
    :return: Challenge class
    """
    cls = CHALLENGE_CLASSES.get(class_id)
    if cls is None:
        raise KeyError
    return cls


"""
Global dictionary used to hold all the Challenge Type classes used by CTFd. Insert into this dictionary to register
your Challenge Type.
"""
CHALLENGE_CLASSES = {"standard": CTFdStandardChallenge}


def load(app):
    register_plugin_assets_directory(app, base_path="/plugins/challenges/assets/")

spr888-ctfd/CTFd/utils/config/__init__.py
import os
import time

from flask import current_app as app

from CTFd.constants.themes import DEFAULT_THEME
from CTFd.utils import get_app_config, get_config
from CTFd.utils.modes import TEAMS_MODE, USERS_MODE


def ctf_name():
    name = get_config("ctf_name")
    return name if name else "CTFd"


def user_mode():
    return get_config("user_mode")


def is_users_mode():
    return user_mode() == USERS_MODE


def is_teams_mode():
    return user_mode() == TEAMS_MODE


def ctf_logo():
    return get_config("ctf_logo")


def ctf_theme():
    theme = get_config("ctf_theme")
    return theme if theme else ""


def ctf_theme_candidates():
    yield ctf_theme()
    if bool(get_app_config("THEME_FALLBACK")):
        yield DEFAULT_THEME


def is_setup():
    return bool(get_config("setup")) is True


def is_scoreboard_frozen():
    freeze = get_config("freeze")

    if freeze:
        freeze = int(freeze)
        if freeze < time.time():
            return True

    return False


def can_send_mail():
    return mailserver() or mailgun()


def get_mail_provider():
    mail_provider = app.config.get("MAIL_PROVIDER")
    if mail_provider:
        return mail_provider
    if get_config("mail_server") and get_config("mail_port"):
        return "smtp"
    if get_config("mailgun_api_key") and get_config("mailgun_base_url"):
        return "mailgun"
    if app.config.get("MAIL_SERVER") and app.config.get("MAIL_PORT"):
        return "smtp"
    if app.config.get("MAILGUN_API_KEY") and app.config.get("MAILGUN_BASE_URL"):
        return "mailgun"


def mailgun():
    if app.config.get("MAILGUN_API_KEY") and app.config.get("MAILGUN_BASE_URL"):
        return True
    if get_config("mailgun_api_key") and get_config("mailgun_base_url"):
        return True
    return False


def mailserver():
    if app.config.get("MAIL_SERVER") and app.config.get("MAIL_PORT"):
        return True
    if get_config("mail_server") and get_config("mail_port"):
        return True
    return False


def get_themes():
    dir = os.path.join(app.root_path, "themes")
    return [
        name
        for name in os.listdir(dir)
        if os.path.isdir(os.path.join(dir, name)) and name != "admin"
    ]

spr888-ctfd/CTFd/themes/admin/templates/configs/accounts.html
<div role="tabpanel" class="tab-pane config-section" id="accounts">

	{% set verify_emails = "true" if verify_emails == True else "false" %}
	{% set name_changes = "true" if name_changes == True else "false" %}
	{% set team_creation = "false" if team_creation == False else "true" %}
	{% with form = Forms.config.AccountSettingsForm(verify_emails=verify_emails, name_changes=name_changes, team_disbanding=team_disbanding, team_creation=team_creation) %}
	<form method="POST" autocomplete="off" class="w-100">
		<ul class="nav nav-tabs mb-3">
			<li class="nav-item">
				<a class="nav-link active" href="#user-accounts" aria-controls="user-accounts" role="tab" data-toggle="tab">
					User Accounts
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#team-accounts" aria-controls="team-accounts" role="tab" data-toggle="tab">
					Team Accounts
				</a>
			</li>
		</ul>

		<div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="user-accounts">
				<div id="user-accounts">
					<div class="form-group">
						{{ form.domain_whitelist.label }}
						{{ form.domain_whitelist(class="form-control", value=domain_whitelist or "") }}
						<small class="form-text text-muted">
							{{ form.domain_whitelist.description }}
						</small>
					</div>

					<div class="form-group">
						{{ form.domain_blacklist.label }}
						{{ form.domain_blacklist(class="form-control", value=domain_blacklist or "") }}
						<small class="form-text text-muted">
							{{ form.domain_blacklist.description }}
						</small>
					</div>
			
					<div class="form-group">
						{{ form.verify_emails.label }}
						{{ form.verify_emails(class="form-control custom-select") }}
						<small class="form-text text-muted">
							{{ form.verify_emails.description }}
						</small>
					</div>
			
					<div class="form-group">
						{{ form.num_users.label }}
						{{ form.num_users(class="form-control", value=num_users) }}
						<small class="form-text text-muted">
							{{ form.num_users.description }}
						</small>
					</div>
			
					<div class="form-group">
						{{ form.incorrect_submissions_per_min.label }}
						{{ form.incorrect_submissions_per_min(class="form-control", value=incorrect_submissions_per_min) }}
						<small class="form-text text-muted">
							{{ form.incorrect_submissions_per_min.description }}
						</small>
					</div>
			
					<div class="form-group">
						{{ form.name_changes.label }}
						{{ form.name_changes(class="form-control custom-select") }}
						<small class="form-text text-muted">
							{{ form.name_changes.description }}
						</small>
					</div>
				</div>
			</div>
			<div role="tabpanel" class="tab-pane" id="team-accounts">
				<div id="team-accounts">
					<div class="form-group">
						{{ form.team_creation.label }}
						{{ form.team_creation(class="form-control", value=team_creation) }}
						<small class="form-text text-muted">
							{{ form.team_creation.description }}
						</small>
					</div>
			
					<div class="form-group">
						{{ form.team_size.label }}
						{{ form.team_size(class="form-control", value=team_size) }}
						<small class="form-text text-muted">
							{{ form.team_size.description }}
						</small>
					</div>
			
					<div class="form-group">
						{{ form.num_teams.label }}
						{{ form.num_teams(class="form-control", value=num_teams) }}
						<small class="form-text text-muted">
							{{ form.num_teams.description }}
						</small>
					</div>

					<div class="form-group">
						{{ form.team_disbanding.label }}
						{{ form.team_disbanding(class="form-control", value=team_disbanding) }}
						<small class="form-text text-muted">
							{{ form.team_disbanding.description }}
						</small>
					</div>
				</div>
			</div>
		</div>

		{{ form.submit(class="btn btn-md btn-primary float-right") }}
	</form>
	{% endwith %}
</div>

spr888-ctfd/CTFd/themes/admin/templates/configs/backup.html
<div role="tabpanel" class="tab-pane config-section" id="backup">
	<ul class="nav nav-tabs mb-3" role="tablist">
		<li class="nav-item">
			<a class="nav-link active" href="#export-ctf" aria-controls="export-ctf" role="tab" data-toggle="tab">Export</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="#import-ctf" aria-controls="import-ctf" role="tab" data-toggle="tab">Import</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="#save-csv" aria-controls="save-csv" role="tab" data-toggle="tab">Download CSV</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="#import-csv" aria-controls="import-csv" role="tab" data-toggle="tab">Import CSV</a>
		</li>
	</ul>
	<div class="tab-content">
		<div role="tabpanel" class="tab-pane active" id="export-ctf">
			<div class="form-group">
				<p>Exports are an archive of your CTF in its current state. They can be re-imported into other CTFd
					instances or used by scripts and third parties to calculate statistics.</p>
				<p>To download an export click the button below.</p>
			</div>
			<div class="form-group">
				<a href="{{ url_for('admin.export_ctf') }}" id="export-button" class="btn btn-warning">Export</a>
			</div>
		</div>
		<div role="tabpanel" class="tab-pane" id="import-ctf">
			<div class="form-group">
				<p>You can import saved CTFd exports by uploading them below. This will completely wipe your existing
					CTFd instance and all your data will be replaced by the imported data.
					You should only import data that you trust!</p>

				<div class="alert alert-warning" role="alert">
					<small class="text-muted text-right">
						<i class="fas fa-exclamation pr-2"></i>
						Importing a CTFd export will completely wipe your existing data
					</small>
				</div>
			</div>
			<div class="form-group">
				<label for="container-files">Import File</label>
				<input class="form-control-file" type="file" name="backup" id="import-file" accept=".zip">
			</div>
			<input id="import-button" type="submit" class="btn btn-warning" value="Import">
		</div>
		<div role="tabpanel" class="tab-pane" id="save-csv">
			<div class="alert alert-warning" role="alert">
				<small class="text-muted text-right">
					<i class="fas fa-exclamation pr-2"></i>
					CSVs exported from CTFd are not guaranteed to import back in via the Import CSV functionality. See <a href="https://docs.ctfd.io/docs/imports/csv/" target="_blank">CSV Importing instructions</a> for details.
				</small>
			</div>
			{% with form = Forms.config.ExportCSVForm() %}
			<form method="GET" action="{{ url_for('admin.export_csv') }}">
				<div class="form-group">
					{{ form.table.label }}
					{{ form.table(class="form-control custom-select") }}
				</div>
				<input type="submit" class="btn btn-warning" value="Download CSV">
			</form>
			{% endwith %}
		</div>
		<div role="tabpanel" class="tab-pane" id="import-csv">
			{% with form = Forms.config.ImportCSVForm() %}
			<form method="POST" action="{{ url_for('admin.import_csv') }}" enctype="multipart/form-data" id="import-csv-form">
				<div class="form-group">
					<div class="alert alert-info" role="alert">
						<small class="text-muted text-right">
							<a href="https://docs.ctfd.io/docs/imports/csv/" target="_blank">
								<i class="far fa-question-circle pr-2"></i> Instructions and CSV templates
							</a>
						</small>
					</div>
				</div>
				<div class="form-group">
					<b>{{ form.csv_type.label }}</b>
					{{ form.csv_type(class="form-control custom-select", id="import-csv-type") }}
					<small class="form-text text-muted">
						{{ form.csv_type.description }}
					</small>
				</div>
				<div class="form-group">
					<b>{{ form.csv_file.label }}</b>
					{{ form.csv_file(class="form-control-file", id="import-csv-file", accept=".csv") }}
					<small class="form-text text-muted">
						{{ form.csv_file.description }}
					</small>
				</div>
				{{ form.nonce() }}
				<input type="submit" class="btn btn-warning" value="Import CSV">
			</form>
			{% endwith %}
		</div>
	</div>
</div>

spr888-ctfd/CTFd/themes/admin/templates/configs/challenges.html
<div role="tabpanel" class="tab-pane config-section" id="challenges">
    {% set hints_free_public_access = "true" if hints_free_public_access == True else "false" %}
	{% 
		with form = Forms.config.ChallengeSettingsForm(
			hints_free_public_access=hints_free_public_access,
		) 
	%}
	<form method="POST" autocomplete="off" class="w-100">
		<div class="form-group">
			{{ form.hints_free_public_access.label }}
			{{ form.hints_free_public_access(class="form-control custom-select") }}
			<small class="form-text text-muted">
				{{ form.hints_free_public_access.description }}
			</small>
		</div>

		<button type="submit" class="btn btn-md btn-primary float-right">Update</button>
	</form>
	{% endwith %}
</div>

spr888-ctfd/CTFd/themes/admin/templates/configs/fields.html
<div role="tabpanel" class="tab-pane config-section" id="fields">
	<form method="POST" autocomplete="off" class="w-100">
		<h5>Custom Fields</h5>

		<small class="form-text text-muted">
			Add custom fields to get additional data from your participants
		</small>

		<ul class="nav nav-tabs mt-3" role="tablist">
			<li class="nav-item active">
				<a class="nav-link active" href="#user-fields" role="tab" data-toggle="tab">
					Users
				</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#team-fields" role="tab" data-toggle="tab">
					Teams
				</a>
			</li>
		</ul>

		<div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="user-fields">
				<div class="col-md-12 py-3">
					<small>Custom user fields are shown during registration. Users can optionally edit these fields in their profile.</small>
				</div>

				<div id="user-field-list" class="pt-3">
				</div>
			</div>
			<div role="tabpanel" class="tab-pane" id="team-fields">
				<div class="col-md-12 py-3">
					<small>Custom team fields are shown during team creation. Team captains can optionally edit these fields in the team profile.</small>
				</div>

				<div id="team-field-list" class="pt-3">
				</div>
			</div>
		</div>
	</form>
</div>

spr888-ctfd/CTFd/themes/admin/templates/configs/general.html
<div role="tabpanel" class="tab-pane config-section active" id="general">
	<form method="POST" autocomplete="off" class="w-100">
		<div class="form-group">
			<label for="ctf_name">
				Event Name
				<small class="form-text text-muted">When no logo is specified, the CTF's name is used instead.</small>
			</label>
			<input class="form-control" id='ctf_name' name='ctf_name' type='text' placeholder="CTF Name"
				{% if ctf_name is defined and ctf_name != None %}value="{{ ctf_name }}"{% endif %}>
		</div>

		<div class="form-group">
			<label>
				Event Description<br>
				<!-- TODO: Clarify WHERE this description is used. -->
				<small class="form-text text-muted">
					Description of your CTF. Available for use on your custom pages and emails as <code>{ctf_description}</code>.
				</small>
			</label>
			<textarea class="form-control" type="text" id="ctf_description" name="ctf_description" rows="5">{{ ctf_description }}</textarea>
		</div>

		<button type="submit" class="btn btn-md btn-primary float-right">Update</button>
	</form>
</div>

spr888-ctfd/CTFd/themes/admin/templates/configs/localization.html
<div role="tabpanel" class="tab-pane config-section" id="localization">
	{% 
		with form = Forms.config.LocalizationForm(
			default_locale=default_locale
		) 
	%}
	<form method="POST" autocomplete="off" class="w-100">
		<div class="form-group">
			{{ form.default_locale.label }}
			{{ form.default_locale(class="form-control custom-select") }}
			<small class="form-text text-muted">
				{{ form.default_locale.description }}
			</small>
		</div>

		<button type="submit" class="btn btn-md btn-primary float-right">Update</button>
	</form>
	{% endwith %}
</div>

spr888-ctfd/CTFd/themes/admin/templates/configs/pause.html
<div role="tabpanel" class="tab-pane config-section" id="pause">
	<form method="POST" autocomplete="off" class="w-100">
		<div class="form-group">
			<div class="form-check pl-0">
				<label>
					<input id="paused" name="paused" type="checkbox" {% if paused %}checked{% endif %}>
					Pause CTF
				</label>
			</div>
			<small class="form-text text-muted">
				Prevent users from submitting answers until unpaused. Challenges can still be viewed.
			</small>
		</div>

		<button type="submit" class="btn btn-md btn-primary float-right">Update</button>
	</form>
</div>